my_file = open("my_file2.txt", "r")
data = my_file.read()
print(f"Данные в файле: \n {data}")
my_file = open("my_file2.txt", "r")
data = my_file.readlines()
print(f"Колличество строк в файле: {len(data)}")
my_file = open("my_file2.txt", "r")
data = my_file.readlines()
for i in range(len(data)):
    print(f"Колличество символов {i + 1}, количество строк: {len(data[i])}")
my_file = open("my_file2.txt", "r")
data = my_file.read()
data = data.split()
print(f"Общее количество слов: {len(data)}")
my_file.close()